In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
# import metrics to compute accuracy
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix
from sklearn.svm import SVC

c:\Users\kshag\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


In [2]:

data = pd.read_excel('StressLevelDataset.xlsx')
data.head(10)

anxiety_level  self_esteem  mental_health_history  depression  headache  \
0             14           20                      0          11         2   
1             15            8                      1          15         5   
2             12           18                      1          14         2   
3             16           12                      1          15         4   
4             16           28                      0           7         2   
5             20           13                      1          21         3   
6              4           26                      0           6         1   
7             17            3                      1          22         4   
8             13           22                      1          12         3   
9              6            8                      0          27         4   

   blood_pressure  sleep_quality  breathing_problem  noise_level  \
0               1              2                  4            2   
1               3              1                  4            3   
2               1              2                  2            2   
3               3              1                  3            4   
4               3              5                  1            3   
5               3              1                  4            3   
6               2              4                  1            1   
7               3              1                  5            3   
8               1              2                  4            3   
9               3              1                  2            0   

   living_conditions  ...  basic_needs  study_load  \
0                  3  ...            2           2   
1                  1  ...            2           4   
2                  2  ...            2           3   
3                  2  ...            2           4   
4                  2  ...            3           3   
5                  2  ...            1           5   
6                  4  ...            4           1   
7                  1  ...            1           3   
8                  3  ...            3           3   
9                  5  ...            2           2   

   teacher_student_relationship  future_career_concerns  social_support  \
0                             3                       3               2   
1                             1                       5               1   
2                             3                       2               2   
3                             1                       4               1   
4                             1                       2               1   
5                             2                       5               1   
6                             4                       1               3   
7                             2                       4               1   
8                             2                       3               3   
9                             1                       5               1   

   peer_pressure  extracurricular_activities  bullying  stress_level  \
0              3                           3         2             1   
1              4                           5         5             2   
2              3                           2         2             1   
3              4                           4         5             2   
4              5                           0         5             1   
5              4                           4         5             2   
6              2                           2         1             0   
7              4                           4         5             2   
8              3                           2         2             1   
9              5                           3         4             1   

   academic_performance  
0                     3  
1                     1  
2                     2  
3                     2  
4                     4  
5                     2  

In [3]:
df = data.dropna() # drops NaN values 
print(df[df.isna().any(axis=1)]) # shows NaN values in data frame if it exists

# Splitting the dataset
features = df.drop(columns = ['academic_performance'])  # features
target = df['academic_performance']  # target variable

features.head()

Empty DataFrame
Columns: [anxiety_level, self_esteem, mental_health_history, depression, headache, blood_pressure, sleep_quality, breathing_problem, noise_level, living_conditions, safety, basic_needs, study_load, teacher_student_relationship, future_career_concerns, social_support, peer_pressure, extracurricular_activities, bullying, stress_level, academic_performance]
Index: []

[0 rows x 21 columns]


anxiety_level  self_esteem  mental_health_history  depression  headache  \
0             14           20                      0          11         2   
1             15            8                      1          15         5   
2             12           18                      1          14         2   
3             16           12                      1          15         4   
4             16           28                      0           7         2   

   blood_pressure  sleep_quality  breathing_problem  noise_level  \
0               1              2                  4            2   
1               3              1                  4            3   
2               1              2                  2            2   
3               3              1                  3            4   
4               3              5                  1            3   

   living_conditions  safety  basic_needs  study_load  \
0                  3       3            2           2   
1                  1       2            2           4   
2                  2       3            2           3   
3                  2       2            2           4   
4                  2       4            3           3   

   teacher_student_relationship  future_career_concerns  social_support  \
0                             3                       3               2   
1                             1                       5               1   
2                             3                       2               2   
3                             1                       4               1   
4                             1                       2               1   

   peer_pressure  extracurricular_activities  bullying  stress_level  
0              3                           3         2             1  
1              4                           5         5             2  
2              3                           2         2             1  
3              4                           4         5             2  
4              5                           0         5             1

In [4]:
target.head(10)

0    3
1    1
2    2
3    2
4    4
5    2
6    5
7    1
8    3
9    2
Name: academic_performance, dtype: int64

In [5]:
## using standard scaler instead of min max scaler
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

# Fit and transform the data
attr = pd.DataFrame(scaler.fit_transform(features), columns=features.columns)
attr.head()

anxiety_level  self_esteem  mental_health_history  depression  headache  \
0       0.480208     0.248612              -0.985559   -0.201393 -0.360741   
1       0.643746    -1.093590               1.014653    0.316508  1.768859   
2       0.153131     0.024912               1.014653    0.187033 -0.360741   
3       0.807284    -0.646189               1.014653    0.316508  1.058992   
4       0.807284     1.143414              -0.985559   -0.719293 -0.360741   

   blood_pressure  sleep_quality  breathing_problem  noise_level  \
0       -1.418416      -0.426445           0.890211    -0.488949   
1        0.981981      -1.072574           0.890211     0.264334   
2       -1.418416      -0.426445          -0.538282    -0.488949   
3        0.981981      -1.072574           0.175964     1.017616   
4        0.981981       1.511942          -1.252529     0.264334   

   living_conditions    safety  basic_needs  study_load  \
0           0.430695  0.186924    -0.539196   -0.472800   
1          -1.357096 -0.524551    -0.539196    1.047901   
2          -0.463200  0.186924    -0.539196    0.287551   
3          -0.463200 -0.524551    -0.539196    1.047901   
4          -0.463200  0.898398     0.158587    0.287551   

   teacher_student_relationship  future_career_concerns  social_support  \
0                      0.254213                0.229550        0.112839   
1                     -1.190927                1.537869       -0.841952   
2                      0.254213               -0.424609        0.112839   
3                     -1.190927                0.883709       -0.841952   
4                     -1.190927               -0.424609       -0.841952   

   peer_pressure  extracurricular_activities  bullying  stress_level  
0       0.186334                    0.164249 -0.403377      0.004428  
1       0.888277                    1.575763  1.557071      1.222011  
2       0.186334                   -0.541508 -0.403377      0.004428  
3       0.888277                    0.870006  1.557071      1.222011  
4       1.590220                   -1.953023  1.557071      0.004428

In [6]:

attr_train, attr_test, target_train,target_test  = train_test_split(attr, target,test_size = 0.25, random_state = 4, shuffle = True)
target_train.head()
# attr_train.head()
target_test.head()

704     5
236     2
88      2
1094    2
251     3
Name: academic_performance, dtype: int64

In [7]:
# import SVM classifier
from sklearn.svm import SVC
# import metrics to compute accuracy
from sklearn.metrics import accuracy_score

# instantiate classifier 
svc=SVC() 

# fit classifier to training set
svc.fit(attr_train,target_train)

# make predictions on test set
target_pred=svc.predict(attr_test)

# compute and print accuracy score
print('Model accuracy score with default hyperparameters: {0:0.4f}'. format(accuracy_score(target_test, target_pred)))
print()
print('Classification Report')
print(classification_report(target_test, target_pred))
print()
print('Confusion Matrix')
print(confusion_matrix(target_test, target_pred))

Model accuracy score with default hyperparameters: 0.4145

Classification Report
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         4
           1       0.41      0.79      0.54        42
           2       0.46      0.43      0.45        99
           3       0.56      0.11      0.18        47
           4       0.26      0.15      0.19        47
           5       0.41      0.72      0.52        36

    accuracy                           0.41       275
   macro avg       0.35      0.37      0.31       275
weighted avg       0.42      0.41      0.37       275


Confusion Matrix
[[ 0  0  2  0  2  0]
 [ 0 33  5  0  3  1]
 [ 1 45 43  4  6  0]
 [ 0  2 35  5  3  2]
 [ 0  0  5  0  7 35]
 [ 1  0  3  0  6 26]]
